#!/bin/bash

# API Key Management Script for Jared's Not Funny
# This script manages API keys securely using Bitwarden CLI

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

# Check if Bitwarden CLI is installed
check_bitwarden() {
    if ! command -v bw &> /dev/null; then
        print_error "Bitwarden CLI not found. Please install it first:"
        echo "  macOS: brew install bitwarden-cli"
        echo "  Linux: sudo apt install bitwarden-cli"
        echo "  Windows: winget install Bitwarden.CLI"
        exit 1
    fi
    print_success "Bitwarden CLI found"
}

# Login to Bitwarden
login_bitwarden() {
    print_warning "Please login to Bitwarden..."
    bw login
    export BW_SESSION=$(bw unlock --raw)
    print_success "Logged in to Bitwarden"
}

# Store API key securely
store_api_key() {
    local key_name="$1"
    local key_value="$2"
    local key_description="$3"
    
    if [ -z "$key_name" ] || [ -z "$key_value" ]; then
        print_error "Key name and value are required"
        echo "Usage: $0 store <key_name> <key_value> [description]"
        exit 1
    fi
    
    local json_item=$(cat <<EOF
{
  "type": 1,
  "name": "$key_name",
  "notes": "$key_description",
  "secureNote": {
    "type": 0,
    "content": "$key_value"
  }
}
EOF
)
    
    echo "$json_item" | bw create item --session "$BW_SESSION"
    print_success "Stored API key: $key_name"
}

# Retrieve API key
get_api_key() {
    local key_name="$1"
    
    if [ -z "$key_name" ]; then
        print_error "Key name is required"
        echo "Usage: $0 get <key_name>"
        exit 1
    fi
    
    local key_value=$(bw get item "$key_name" --session "$BW_SESSION" | jq -r '.login.password // .secureNote.content // .notes')
    
    if [ -z "$key_value" ] || [ "$key_value" = "null" ]; then
        print_error "Key '$key_name' not found"
        exit 1
    fi
    
    echo "$key_value"
}

# List all API keys
list_api_keys() {
    print_warning "Available API keys:"
    bw list items --session "$BW_SESSION" | jq -r '.[] | select(.type == 1) | "- \(.name): \(.notes // "No description")"'
}

# Export keys to environment (for development)
export_to_env() {
    local env_file=".env"
    
    if [ -f "$env_file" ]; then
        print_warning "Backing up existing .env file to .env.backup"
        cp "$env_file" "$env_file.backup"
    fi
    
    echo "# Generated by api-key-manager.sh" > "$env_file"
    echo "# Add this to .gitignore" >> "$env_file"
    echo "" >> "$env_file"
    
    # Get common podcast API keys
    local google_analytics_id=$(get_api_key "GOOGLE_ANALYTICS_ID" 2>/dev/null || echo "")
    local youtube_api_key=$(get_api_key "YOUTUBE_API_KEY" 2>/dev/null || echo "")
    local twitter_bearer_token=$(get_api_key "TWITTER_BEARER_TOKEN" 2>/dev/null || echo "")
    local instagram_access_token=$(get_api_key "INSTAGRAM_ACCESS_TOKEN" 2>/dev/null || echo "")
    
    [ -n "$google_analytics_id" ] && echo "GOOGLE_ANALYTICS_ID=$google_analytics_id" >> "$env_file"
    [ -n "$youtube_api_key" ] && echo "YOUTUBE_API_KEY=$youtube_api_key" >> "$env_file"
    [ -n "$twitter_bearer_token" ] && echo "TWITTER_BEARER_TOKEN=$twitter_bearer_token" >> "$env_file"
    [ -n "$instagram_access_token" ] && echo "INSTAGRAM_ACCESS_TOKEN=$instagram_access_token" >> "$env_file"
    
    print_success "Environment variables exported to $env_file"
    print_warning "Remember to add .env to .gitignore!"
}

# Setup YouTube API with limited access
setup_youtube_api() {
    print_warning "Setting up YouTube API with restricted access..."
    
    echo "To set up YouTube API with limited access:"
    echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
    echo "2. Create a new project or select existing"
    echo "3. Enable YouTube Data API v3"
    echo "4. Create credentials -> API Key"
    echo "5. Set these restrictions:"
    echo "   - HTTP referrers: jcsnotfunny.com/*"
    echo "   - API restrictions: YouTube Data API v3 only"
    echo "   - Daily quota: 10,000 units"
    echo ""
    read -p "Enter your YouTube API key: " youtube_key
    
    if [ -n "$youtube_key" ]; then
        store_api_key "YOUTUBE_API_KEY" "$youtube_key" "YouTube API key with video upload permissions - restricted to jcsnotfunny.com"
    fi
}

# Setup Google Analytics
setup_google_analytics() {
    print_warning "Setting up Google Analytics..."
    
    echo "To set up Google Analytics:"
    echo "1. Go to Google Analytics: https://analytics.google.com/"
    echo "2. Create a GA4 property for jcsnotfunny.com"
    echo "3. Create a Data Stream"
    echo "4. Copy the Measurement ID (starts with 'G-')"
    echo ""
    read -p "Enter your GA4 Measurement ID: " ga_id
    
    if [ -n "$ga_id" ]; then
        store_api_key "GOOGLE_ANALYTICS_ID" "$ga_id" "Google Analytics 4 Measurement ID for jcsnotfunny.com"
    fi
}

# Setup social media tokens
setup_social_media() {
    print_warning "Setting up social media API tokens..."
    
    # Twitter/X
    echo "Twitter/X API:"
    read -p "Enter your Twitter Bearer Token: " twitter_token
    if [ -n "$twitter_token" ]; then
        store_api_key "TWITTER_BEARER_TOKEN" "$twitter_token" "Twitter/X Bearer Token for posting content"
    fi
    
    # Instagram
    echo "Instagram Basic Display API:"
    read -p "Enter your Instagram Access Token: " instagram_token
    if [ -n "$instagram_token" ]; then
        store_api_key "INSTAGRAM_ACCESS_TOKEN" "$instagram_token" "Instagram Basic Display Access Token"
    fi
}

# Generate limited access tokens for collaborators
generate_limited_token() {
    local collaborator="$1"
    local duration="${2:-1h}"
    
    print_warning "Generating limited access token for $collaborator..."
    
    # This would integrate with your token service
    # For now, just show the concept
    echo "Limited access token concept:"
    echo "- User: $collaborator"
    echo "- Duration: $duration"
    echo "- Permissions: YouTube upload only, no access to other APIs"
    echo "- IP restrictions: Specific IPs only"
    echo ""
    echo "Implementation would use:"
    echo "- OAuth 2.0 with limited scopes"
    echo "- JWT tokens with expiration"
    echo "- IP whitelisting"
    echo "- Usage quotas and monitoring"
}

# Show usage
show_usage() {
    echo "API Key Manager for Jared's Not Funny"
    echo ""
    echo "Usage: $0 <command> [options]"
    echo ""
    echo "Commands:"
    echo "  store <name> <value> [description]  Store an API key"
    echo "  get <name>                         Retrieve an API key"
    echo "  list                               List all API keys"
    echo "  export                             Export keys to .env file"
    echo "  setup-youtube                       Setup YouTube API key"
    echo "  setup-analytics                    Setup Google Analytics"
    echo "  setup-social                       Setup social media tokens"
    echo "  limited-token <user> [duration]   Generate limited access token"
    echo "  help                               Show this help"
}

# Main script logic
main() {
    check_bitwarden
    
    # Check if logged in
    if ! bw login --check --session "$BW_SESSION" &> /dev/null; then
        login_bitwarden
    fi
    
    case "${1:-help}" in
        "store")
            store_api_key "$2" "$3" "$4"
            ;;
        "get")
            get_api_key "$2"
            ;;
        "list")
            list_api_keys
            ;;
        "export")
            export_to_env
            ;;
        "setup-youtube")
            setup_youtube_api
            ;;
        "setup-analytics")
            setup_google_analytics
            ;;
        "setup-social")
            setup_social_media
            ;;
        "limited-token")
            generate_limited_token "$2" "$3"
            ;;
        "help"|*)
            show_usage
            ;;
    esac
}

# Run main function with all arguments
main "$@"